=== Kongbeng-21/Database/Week10/Chapter3_act1and2_fixed/Activity1/schema-student_db-students-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "age",
    "courses",
    "department",
    "gpa",
    "name",
    "student_id"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "age": {
      "type": "integer"
    },
    "courses": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "department": {
      "type": "string"
    },
    "gpa": {
      "$ref": "#/$defs/Double"
    },
    "name": {
      "type": "string"
    },
    "student_id": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Double": {
      "oneOf": [
        {
          "type": "number"
        },
        {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "enum": [
                "Infinity",
                "-Infinity",
                "NaN"
              ]
            }
          }
        }
      ]
    }
  }
}

=== Kongbeng-21/Database/Week10/Chapter3_act1and2_fixed/Activity1/student_db.students.json
[{
  "_id": {
    "$oid": "6add4ccfc53b637e0e03906a"
  },
  "student_id": "S001",
  "name": "kongbeng",
  "age": 19,
  "department": "engineering",
  "gpa": 3.67,
  "courses": [
    "compro2",
    "DBMS"
  ]
},
{
  "_id": {
    "$oid": "6add4d2fc53b637e0e03906c"
  },
  "student_id": "S003",
  "name": "Boom",
  "age": 21,
  "department": "engineering",
  "gpa": 3.1,
  "courses": [
    "ML"
  ]
},
{
  "_id": {
    "$oid": "6add4e1a3d9372f54bdbd3fa"
  },
  "student_id": "S004",
  "name": "w1n",
  "age": 20,
  "department": "CS",
  "gpa": 3.5,
  "courses": [
    "DBMS",
    "Network"
  ]
}]
