=== Kongbeng-21/Database/Week10/Chapter3_act1and2_fixed/Activity2/schema-instagram_db-users-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "created_at",
    "followers",
    "following",
    "username"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "created_at": {
      "$ref": "#/$defs/Date"
    },
    "followers": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "following": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "username": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== Kongbeng-21/Database/Week10/Chapter3_act1and2_fixed/Activity2/instagram_db.users.json
[{
  "_id": {
    "$oid": "6ade39a108a40dbfc3b4897a"
  },
  "username": "Kongbeng",
  "followers": [
    "Boom"
  ],
  "following": [
    "Boom"
  ],
  "created_at": {
    "$date": "2026-10-26T00:17:21.380Z"
  }
},
{
  "_id": {
    "$oid": "6ade39c008a40dbfc3b4897c"
  },
  "username": "Boom",
  "followers": [
    "Kongbeng"
  ],
  "following": [
    "Kongbeng"
  ],
  "created_at": {
    "$date": "2026-10-26T00:17:52.776Z"
  }
}]
