=== Kongbeng-21/Database/Week10/Chapter3_act1and2_fixed/Activity2/schema-instagram_db-posts-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "caption",
    "comments",
    "created_at",
    "image_url",
    "username"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "caption": {
      "type": "string"
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "created_at",
          "text",
          "username"
        ],
        "properties": {
          "created_at": {
            "$ref": "#/$defs/Date"
          },
          "text": {
            "type": "string"
          },
          "username": {
            "type": "string"
          }
        }
      }
    },
    "created_at": {
      "$ref": "#/$defs/Date"
    },
    "image_url": {
      "type": "string"
    },
    "username": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== Kongbeng-21/Database/Week10/Chapter3_act1and2_fixed/Activity2/instagram_db.posts.json
[{
  "_id": {
    "$oid": "6ade39ae08a40dbfc3b4897b"
  },
  "username": "Kongbeng",
  "caption": "Learning MongoDB!",
  "image_url": "https://picsum.photos/400",
  "created_at": {
    "$date": "2026-10-26T00:17:34.495Z"
  },
  "comments": [
    {
      "username": "Boom",
      "text": "Nice",
      "created_at": {
        "$date": "2026-10-26T00:18:02.296Z"
      }
    }
  ]
}]
